CREATE TABLE BUILDING(
    BID          VARCHAR2(50),
    BNAME        VARCHAR2(50) NOT NULL,
    VERTEX_NUM   NUMBER NOT NULL,
    BZONE        SDO_GEOMETRY NOT NULL,
    CONSTRAINT "BUILDING_ID" PRIMARY KEY ("BID") 
);

INSERT INTO USER_SDO_GEOM_METADATA
    (TABLE_NAME,
     COLUMN_NAME,
     DIMINFO,
     SRID)
    VALUES (
    'BUILDING',
    'BZONE',
    SDO_DIM_ARRAY(
      SDO_DIM_ELEMENT('X', 0, 580, 1),
      SDO_DIM_ELEMENT('Y', 0, 820, 1)
       ),
    NULL
);

CREATE INDEX BUILDING_ZONE ON BUILDING(BZONE)
INDEXTYPE IS MDSYS.SPATIAL_INDEX;

CREATE TABLE STUDENT(
    STUID          VARCHAR2(50),
    STULOC    SDO_GEOMETRY NOT NULL,
    CONSTRAINT "STUDENT_ID" PRIMARY KEY ("STUID")
);

INSERT INTO USER_SDO_GEOM_METADATA
    (TABLE_NAME,
     COLUMN_NAME,
     DIMINFO,
     SRID)
    VALUES (
    'STUDENT',
    'STULOC',
    SDO_DIM_ARRAY(
      SDO_DIM_ELEMENT('X', 0, 580, 1),
      SDO_DIM_ELEMENT('Y', 0, 820, 1)
       ),
    NULL
);

CREATE INDEX STUDENT_LOC ON STUDENT(STULOC)
INDEXTYPE IS MDSYS.SPATIAL_INDEX;

CREATE TABLE ASYS(
    ASID          VARCHAR2(50),
    ASRADIUS      NUMBER,
    ASCENTER      SDO_GEOMETRY NOT NULL,
    ASZONE        SDO_GEOMETRY NOT NULL,
    CONSTRAINT "ANNOUNCE_SYS_ID" PRIMARY KEY ("ASID")
);

INSERT INTO USER_SDO_GEOM_METADATA
    (TABLE_NAME,
     COLUMN_NAME,
     DIMINFO,
     SRID)
    VALUES (
    'ASYS',
    'ASCENTER',
    SDO_DIM_ARRAY(
      SDO_DIM_ELEMENT('X', 0, 580, 1),
      SDO_DIM_ELEMENT('Y', 0, 820, 1)
       ),
    NULL
);

INSERT INTO USER_SDO_GEOM_METADATA
    (TABLE_NAME,
     COLUMN_NAME,
     DIMINFO,
     SRID)
    VALUES (
    'ASYS',
    'ASZONE',
    SDO_DIM_ARRAY(
      SDO_DIM_ELEMENT('X', 0, 580, 1),
      SDO_DIM_ELEMENT('Y', 0, 820, 1)
       ),
    NULL
);

CREATE INDEX ASYS_ASCENTER ON ASYS(ASCENTER)
INDEXTYPE IS MDSYS.SPATIAL_INDEX;

CREATE INDEX ASYS_ASZONE ON ASYS(ASZONE)
INDEXTYPE IS MDSYS.SPATIAL_INDEX;

COMMIT;